services:
  cig-clicker-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "2567:2567"
    environment:
      - NODE_ENV=development

  cig-clicker-client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - VITE_SERVER_URL=http://localhost:2567
    ports:
      - "3001:80"
    depends_on:
      - cig-clicker-server